### ISSUE TITLE
File "./composer.json" cannot be found in the current directory

### ISSUE THREAD

**Issue by patriziotomato** [judge2020/actions-laravel-nova-composer-login#1]
While running the action I get this:

> File "./composer.json" cannot be found in the current directory

This file exists

**Comment by patriziotomato** [comment]
Added it after checkout action I get this:

>   [RuntimeException]                           
 > http-basic.nova.laravel.com is not defined.

**Comment by judge2020** [comment]
This was made for the old HCL syntax Actions, I should have archived it before now. Since Actions is now using the YML syntax, you should do the following:

```yml
      - name: Login to Laravel Nova
        run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
```
With those secrets set. The Password should be the API token from https://nova.laravel.com/settings#password.
